server:
  port:
    http: 80
    https: 443

container:
  image: n3r0ch/ddesktop-client
  pull: true
  prefix: dd--
  wsport: 6080
  cpushares: 256
  memory: 1024

ssl:
  cert: /etc/ddesktop/cert.pem
  key: /etc/ddesktop/key.pem

htpasswd:
  path: /etc/ddesktop/.htpasswd